name: Update Stars Automatically

on:
  schedule:
    - cron: '0 2 * * *' # Runs every day at 2:00 AM UTC
  workflow_dispatch: # Allows you to run it manually from the GitHub website

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the bot to push changes to the README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_stars.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Matteo Celani"
          git config --global user.email "26189482+matteocelani@users.noreply.github.com"
          git add README.md
          # Ignores the error if there are no new stars to update
          git commit -m "Automated update: fetched new stars" || exit 0
          git push
